### ISSUE TITLE
Misnamed File

### ISSUE THREAD

**Issue by phlco** [jessleenyc/lendingBot#1]
Careful! Your `index.html` file is misnamed `html.index`

**Comment by jessleenyc** [comment]
yes i saw, thanks! should be resolved by now. quick question---how do I delete repositories on github? I already deleted the files on my computer through the terminal.

**Comment by phlco** [comment]
Take a look at the "settings" link from your project page. Scroll down and click on "delete repository". You'll have to enter the name of your repo to confirm.
